import "./globals.css";
import { Roboto, Oleo_Script } from "next/font/google";
import Nav from "@/components/Nav";
import Hydrate from "@/components/Hydrate";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <Hydrate>
        {children}
        <Nav />
      </Hydrate>
    </html>
  );
}
